version: '3.6'

services:
    defshop_php:
        build:
          context: .
          target: develop
        container_name: defshop_php
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        links:
            - defshop_mysql
        volumes:
            - .:/var/www
            - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

    defshop_mysql:
        image: mysql:8
        container_name: defshop_mysql
        environment:
            - MYSQL_ROOT_PASSWORD=defshop
            - MYSQL_DATABASE=defshop
            - MYSQL_USER=defshop
            - MYSQL_PASSWORD=defshop
        volumes:
            - defshop-mysql-data:/var/lib/mysql
        ports:
            - 3307:3306

volumes:
    defshop-mysql-data:
